# Site settings
title: Thomas Countz
email: thomascountz@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Rails Developer || NYC
baseurl:  ""
url:  "https://thomascountz.github.io"
twitter_username: thomascountz
github_username:  thomascountz

# Build settings
markdown: kramdown

highlighter: pygments

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"
gems: 
  - jekyll-paginate

collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/



